# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_xbar_1/accumulator_block_xbar_1.xci
# IP: The module: 'accumulator_block_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_xbar_1/accumulator_block_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_xbar_1/accumulator_block_xbar_1.xci
# IP: The module: 'accumulator_block_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_xbar_1/accumulator_block_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
