#pragma line 1 "hls_macc.c" ::: -10
#pragma line 1 "hls_macc.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado/2018.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 300 "C:/Xilinx/Vivado/2018.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 3
#pragma line 8 "<command line>" 2 ::: 121
#pragma line 1 "<built-in>" 2 ::: 122
#pragma line 1 "hls_macc.c" 2 ::: 123
#pragma line 1 "./hls_macc.h" 1 ::: 124
#pragma line 1 "C:/Xilinx/Vivado/2018.1/win64/tools/clang/bin/../lib/clang/3.1/include\\stdbool.h" 1 3 4 ::: 128
#pragma line 5 "./hls_macc.h" 2 ::: 129
#pragma line 2 "hls_macc.c" 2 ::: 132
