#pragma line 1 "hls_macc.c" ::: 0
#pragma line 1 "hls_macc.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 147 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado/2018.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 300 "C:/Xilinx/Vivado/2018.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 13
#pragma line 8 "<command line>" 2 ::: 131
#pragma line 1 "<built-in>" 2 ::: 132
#pragma line 1 "hls_macc.c" 2 ::: 133
#pragma line 1 "./hls_macc.h" 1 ::: 134
#pragma line 1 "C:/Xilinx/Vivado/2018.1/win64/tools/clang/bin/../lib/clang/3.1/include\\stdbool.h" 1 3 4 ::: 138
#pragma line 5 "./hls_macc.h" 2 ::: 139
#pragma line 2 "hls_macc.c" 2 ::: 142
