# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.BramSDPPropagationFix 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config  -ruleid {3}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {4}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xcvu9p-flga2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.cache/wt [current_project]
set_property parent.project_path C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vcu118:part0:2.0 [current_project]
set_property ip_repo_paths c:/Users/niles/Documents/VivadoProjects/accumulate/hls_macc/vhls_prj/solution1/impl/ip [current_project]
set_property ip_output_repo c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/hdl/accumulator_block_wrapper.v
add_files C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/accumulator_block.bd
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_axi_intc_1/accumulator_block_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_axi_intc_1/accumulator_block_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_axi_intc_1/accumulator_block_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_mdm_1_3/accumulator_block_mdm_1_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_mdm_1_3/accumulator_block_mdm_1_3_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_clk_wiz_1_3/accumulator_block_clk_wiz_1_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_clk_wiz_1_3/accumulator_block_clk_wiz_1_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_clk_wiz_1_3/accumulator_block_clk_wiz_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_rst_clk_wiz_1_100M_3/accumulator_block_rst_clk_wiz_1_100M_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_rst_clk_wiz_1_100M_3/accumulator_block_rst_clk_wiz_1_100M_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_rst_clk_wiz_1_100M_3/accumulator_block_rst_clk_wiz_1_100M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_hls_macc_0_2/constraints/hls_macc_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_xbar_1/accumulator_block_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_dlmb_v10_3/accumulator_block_dlmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_dlmb_v10_3/accumulator_block_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_ilmb_v10_3/accumulator_block_ilmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_ilmb_v10_3/accumulator_block_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_dlmb_bram_if_cntlr_3/accumulator_block_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_ilmb_bram_if_cntlr_3/accumulator_block_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_lmb_bram_3/accumulator_block_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_axi_uart16550_0_0/accumulator_block_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_axi_uart16550_0_0/accumulator_block_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_axi_uart16550_0_0/accumulator_block_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/niles/Documents/VivadoProjects/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/accumulator_block_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top accumulator_block_wrapper -part xcvu9p-flga2104-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef accumulator_block_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file accumulator_block_wrapper_utilization_synth.rpt -pb accumulator_block_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
