# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/accumulator_block/accumulator_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block || ORIG_REF_NAME==accumulator_block} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_microblaze_0_1 || ORIG_REF_NAME==accumulator_block_microblaze_0_1} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_microblaze_0_axi_periph_2/accumulator_block_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_microblaze_0_axi_periph_2 || ORIG_REF_NAME==accumulator_block_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_microblaze_0_axi_intc_1/accumulator_block_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_microblaze_0_axi_intc_1 || ORIG_REF_NAME==accumulator_block_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_microblaze_0_xlconcat_1/accumulator_block_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_microblaze_0_xlconcat_1 || ORIG_REF_NAME==accumulator_block_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_mdm_1_3/accumulator_block_mdm_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_mdm_1_3 || ORIG_REF_NAME==accumulator_block_mdm_1_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_clk_wiz_1_3/accumulator_block_clk_wiz_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_clk_wiz_1_3 || ORIG_REF_NAME==accumulator_block_clk_wiz_1_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_rst_clk_wiz_1_100M_3/accumulator_block_rst_clk_wiz_1_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==accumulator_block_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_hls_macc_0_2/accumulator_block_hls_macc_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_hls_macc_0_2 || ORIG_REF_NAME==accumulator_block_hls_macc_0_2} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_xbar_1/accumulator_block_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_xbar_1 || ORIG_REF_NAME==accumulator_block_xbar_1} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_dlmb_v10_3/accumulator_block_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_dlmb_v10_3 || ORIG_REF_NAME==accumulator_block_dlmb_v10_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_ilmb_v10_3/accumulator_block_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_ilmb_v10_3 || ORIG_REF_NAME==accumulator_block_ilmb_v10_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_dlmb_bram_if_cntlr_3/accumulator_block_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==accumulator_block_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_ilmb_bram_if_cntlr_3/accumulator_block_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==accumulator_block_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_lmb_bram_3/accumulator_block_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_lmb_bram_3 || ORIG_REF_NAME==accumulator_block_lmb_bram_3} -quiet] -quiet

# IP: bd/accumulator_block/ip/accumulator_block_axi_uart16550_0_0/accumulator_block_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_block_axi_uart16550_0_0 || ORIG_REF_NAME==accumulator_block_axi_uart16550_0_0} -quiet] -quiet

# XDC: bd/accumulator_block/accumulator_block_ooc.xdc
