# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1.xci
# IP: The module: 'accumulator_block_microblaze_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1.xci
# IP: The module: 'accumulator_block_microblaze_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/niles/Downloads/Uni/PartIV/DesignFiles/Vivado_HLS_Tutorial/Using_IP_with_Zynq/accumulate/accumulate/accumulate.srcs/sources_1/bd/accumulator_block/ip/accumulator_block_microblaze_0_1/accumulator_block_microblaze_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_block_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
